version: 0.1
log:
  level: debug
  fields:
    service: registry
storage:
  delete:
    enabled: true
  hdfs:
    hdfsrootdirectory: /tmp/gabe-test
    hdfsnamenode: nn-crunchy.bf2.tumblr.net:50070
    hdfsuser: docker
    directoryumask: 0755
http:
  addr: :5000
  debug:
    addr: :6001
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: false
    interval: 10s
    threshold: 3
#maintenance:
#    uploadpurging:
#      enabled: true
#      age: 10m
#      interval: 1m
#      dryrun: false

